### ISSUE TITLE
`execute` does not appear to enforce the handler return type

### ISSUE THREAD

**Issue by michael-wolfenden** [evilkiwi/lamware#1]
**Describe the bug**
When the middleware is defined with a handler that has a return type declared, `execute` does not appear to enforce that return type (it appears to act as `any`)

**To Reproduce**
https://codesandbox.io/s/pedantic-microservice-8odu6h

**Expected behavior**
Given the following:

```typescript
import type { APIGatewayProxyHandlerV2 } from "aws-lambda";
import { lamware } from "@lamware/core";

const middleware = lamware<APIGatewayProxyHandlerV2<{ msg: string }>>();
middleware.execute(async (event) => new Date());
```

I would have expected a compile time error as `execute` does not return a `APIGatewayProxyResultV2<{ msg: string }>`

**Comment by devlsh** [comment]
Fixed in `@lamware/core@1.2.22`
