### ISSUE TITLE
JSON parsing in `secrets-manager`

### ISSUE THREAD

**Issue by moltar** [evilkiwi/lamware#3]
I think this is wrong:

https://github.com/evilkiwi/lamware/blob/fa9d44d64820cc69347672875358be56ae5c4bce/packages/secrets-manager/src/index.ts#L58

Because secrets may contain those characters, especially auto-generated secrets.

Less wrong solutions would be:

- Use try/catch to wrap `JSON.parse` the secret value (this can still fail as `"foo"` is both valid JSON and valid secret string)
- Check for trailing `}` and `]` as well

**Comment by devlsh** [comment]
Good catch - will fix now.

**Comment by devlsh** [comment]
I've opted for `try/catch` with `JSON.parse`, should this become an issue in the future then maybe some more elaborate regex tests can be written (though I'd prefer not to)

Thanks for reporting the issue!
