### ISSUE TITLE
Question on writing middleware

### ISSUE THREAD

**Issue by DaveLo** [evilkiwi/lamware#4]
I am trying to put together a middleware to connect to an influxDB instance. 

This middleware needs secrets passed in from secretsmanager middleware, using `.useSync`.
 
```typescript
const {handler,getState} = lamware()
  .use(secretsmanager({
    region: env.region,
    throwOnError: env.isProd
    secrets: {
      influxKeys: env.influxName
    }
  }))
  .useSync(influxDB(() => {
    const state:Partial<ExampleHandlerState> = getState();
    
    if (!state?.secrets?.influxKeys) {
      throw new Error('Missing keys');
    }

    const keys = state.secrets.influxKeys
    return keys
  })
  .execute(eventhandler)

export handler;
```

The passed function is used in the init phase of the middleware, and it throws because state is undefined.  I feel like I'm probably missing something obvious.

**Comment by devlsh** [comment]
Documentation definitely needs to be better on that front, but you should be passing the state getter from your Middleware.init, e.g. the memoize middleware: https://github.com/evilkiwi/lamware/blob/master/packages/memoize/src/index.ts

**Comment by DaveLo** [comment]
so 
```typescript
.useSync(influxDB((getState) => {
    const state:Partial<ExampleHandlerState> = getState();
    
    if (!state?.secrets?.influxKeys) {
      throw new Error('Missing keys');
    }

    const keys = state.secrets.influxKeys
    return keys
  })
```
this causes some typescript issues when I attempt to implement it in the middleware.

_S doesn't exist on InfluxMiddlewareState_
<img width="946" alt="Screen Shot 2022-07-09 at 6 27 39 PM" src="https://user-images.githubusercontent.com/8697306/178124598-849147c2-5bb8-4505-9557-4f8fb47e4fd0.png">

_Type not assignable_
<img width="970" alt="Screen Shot 2022-07-09 at 6 28 04 PM" src="https://user-images.githubusercontent.com/8697306/178124632-13f42f7e-6ac9-44c5-9b94-c7e9c0f4c0e9.png">

This works on memoize because the closure return is of type `S` (despite eslint/typescript really not liking to see `extends object` 🤷 ).

I'm not sure what the correct strategy is on managing a dependency cascade, I could just forego the secretsmanager middleware entirely and run a secret client inside of my function but at that point I'm basically doing what I would do without the middleware.

**Comment by DaveLo** [comment]
I think I can work around the TS errors with some targeted use of `@ts-ignore` so I'm going to close this, thank you for pointing me in the right direction!

**Comment by devlsh** [comment]
I'll definitely be taking a look at this during the coming week (whether it's just to improve documentation or overhaul state management), but yeah it's a somewhat edge-case of TypeScript usage for compiling the state typings, things like partial state typings with useSync would probably require a more static approach - either way I'll make sure to investigate further

Thanks! 😄

**Comment by DaveLo** [comment]
I wonder if you could make a SyncMiddleware type for non-encapsulated use cases something like 
```typescript
export interface SyncMiddleware<H extends Handler = Handler, S extends object = {}, C extends object = S> extends Middleware<H,S> {
  init?: InitHandler<C>
}
```
This doesn't work out of the box, but maybe something similar?
